languageCode = 'en-us'
title = "Lucas's Webpage"
buildFuture = true
baseURL = "https://scharenbroch.dev/"

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"

[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']
